### ISSUE TITLE
Example of using callback from js module

### ISSUE THREAD

**Issue by drejohnson** [PeteProgrammer/resync#1]
How would I handle a callback?

```
fs.readFile(filePath, "utf8", function(err, data) {
  if (err) throw err;

  // Do something with data
  const document = data...
  // Send the response back to the client
  res.send(document);
});
```

I've been tryng to use:
```
[@bs.module "fs"] external readFile : (string, string, (Js.null(Js.Exn.t), unit) => unit) => unit =
  "";

let filePath = Node_path.resolve("./build", "index.html");
let readFile = (path, unicode) => readFile(path, unicode) |> Async.from_js;

Fs.readFile(filePath, "utf8") |> (
  (data) => {
    let document =
      Js.String.replace(
        {j|<div id="root">|j},
        {j|<div id="root">$html|j},
       data
      );
    Response.sendString(res, document)
  }
)
```

Is this possible? I'm pretty new to Reason, any guidance would be appreciated. Thanks!

**Comment by stroiman** [comment]
It should be possible, I'll try to get a working example later. The `Response.sendString` is that from bs-express? IFAIK, bs-express still have a problem with async code (i have a branch that works though) - https://github.com/reasonml-community/bs-express/issues/14

But as far as I can tell by just looking at the code, your readFile mapping looks good. It's how you use it that needs slight adjustment, something like this:

```
Fs.readFile(filePath, "utf8") 
|> Async.run(
  (data) => {
    let document =
      Js.String.replace(
        {j|<div id="root">|j},
        {j|<div id="root">$html|j},
       data
      );
    Response.sendString(res, document)
  }
)
```

But we could extract the processing into a separate function like this:
```
let processDoc = data => {
    let document =
      Js.String.replace(
        {j|<div id="root">|j},
        {j|<div id="root">$html|j},
       data
      );

Fs.readFile(filePath, "utf8") 
|> Async.map(processDoc)
|> Async.run(
  (doc) => {Response.sendString(res, doc)
  }
)
```
And you could add error handling
```
Fs.readFile(filePath, "utf8") 
|> Async.map(processDoc)
|> Async.run(
  (doc) => {Response.sendString(res, doc),
  ~fe=err => {
    Js.log2("Error occurred", err);
    Response.status(res,500);
    Response.sendString(res, "Internal server error")
  }
  }
)
```

The error handling part is a common pattern in my own project, so I'll probably come up with a generic solution.

But I don't have a Reason dev environment as I'm writing this, so there may be syntax errors

**Comment by drejohnson** [comment]
Thanks. The first example worked.
